// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvn31W0ZSloU_QJTnNtAFHNPcfZ7Hg9Qs',
    appId: '1:687461748677:web:ef328474bcfeaaaa21c5ac',
    messagingSenderId: '687461748677',
    projectId: 'cloud-todo-firestore',
    authDomain: 'cloud-todo-firestore.firebaseapp.com',
    storageBucket: 'cloud-todo-firestore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe0iZ5KYe-mvb1tOg8gqDeMTiz90g8500',
    appId: '1:687461748677:android:99cbda9b3045676f21c5ac',
    messagingSenderId: '687461748677',
    projectId: 'cloud-todo-firestore',
    storageBucket: 'cloud-todo-firestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAspY9NqsEf56yESX0ehN_jPjuumC3bTaU',
    appId: '1:687461748677:ios:35b33c3f697e8f6021c5ac',
    messagingSenderId: '687461748677',
    projectId: 'cloud-todo-firestore',
    storageBucket: 'cloud-todo-firestore.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAspY9NqsEf56yESX0ehN_jPjuumC3bTaU',
    appId: '1:687461748677:ios:35b33c3f697e8f6021c5ac',
    messagingSenderId: '687461748677',
    projectId: 'cloud-todo-firestore',
    storageBucket: 'cloud-todo-firestore.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvn31W0ZSloU_QJTnNtAFHNPcfZ7Hg9Qs',
    appId: '1:687461748677:web:2230b0586117a06b21c5ac',
    messagingSenderId: '687461748677',
    projectId: 'cloud-todo-firestore',
    authDomain: 'cloud-todo-firestore.firebaseapp.com',
    storageBucket: 'cloud-todo-firestore.firebasestorage.app',
  );
}
